# Site settings
title: Christopher Betz
email: christopherwilliambetz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I build stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cbetz.com" # the base hostname & protocol for your site
twitter_username: thechrisbetz
github_username:  cbetz

# Build settings
markdown: kramdown
